
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whnazivwtssnguftpchb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobmF6aXZ3dHNzbmd1ZnRwY2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODA1MDMsImV4cCI6MjA1NzM1NjUwM30.lwnTU_3oZvxTLs1RlHXx9SW8iYou9RJTNACC0XoJE94";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
